spring.application.name=budgeting
spring.ai.openai.api-key=${OPENAI_API_KEY}

#For test purposes. DB configuration for app is on composer.yml
#spring.datasource.url=jdbc:mysql://localhost:3307/transaction
#spring.datasource.username=app
#spring.datasource.password=app

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.ai=DEBUG

spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.language=pt
spring.ai.openai.audio.transcription.options.temperature=0
spring.ai.openai.audio.transcription.options.response-format=text
spring.ai.openai.audio.transcription.options.prompt=Audio em português brasileiro.\
  Áudio contém a descrição de gastos financeiros.\
  As frases geralmente contém:\
  - um valor em reais (número + "reais");\
  - uma ação (gastei, paguei, comprei);\
  - Um local ou estabelecimento (mercado, farmácia, restaurante, loja, etc.)\
  \
  O texto transcrito deve seguir as seguintes regras para valores:\
  - transcreva sempre os valores para "valor", seguido da palavra reais, por exemplo: "4 reais"\
  - não transcreva números por extenso, mas mantenha em formato numérico (ex: 200 reais);

spring.ai.model.audio.speech=openai
spring.ai.openai.audio.speech.options.model=gpt-4o-mini-tts
spring.ai.openai.audio.speech.options.voice=nova
spring.ai.openai.audio.speech.options.speed=1.2
spring.ai.openai.audio.speech.options.response-format=mp3
